### ISSUE TITLE
1.24.0?

### ISSUE THREAD

**Issue by xJon** [jk4837/PlaylistEditor#1]
Would be nice :)

**Comment by jk4837** [comment]
Since the core mod of 1.24.0 has playlistmanager, which already supports all editing functions for playlists, the new PlaylistEditor will remove related functions and keep only a few functions, do you still need this?

**Comment by xJon** [comment]
Hmm, I didn't know of this. What does this mean for existing playlists created with PlaylistEditor in 1.21?

**Comment by jk4837** [comment]
Existing playlists will be brought into 1.24 smoothly, only lock information will be lost.

**Comment by xJon** [comment]
Sounds great, so I'd love to have an updated version so I'll be able to update to 1.24 :)

**Comment by jk4837** [comment]
Maybe I didn’t make it clear enough.
PlaylistEditor plans to retire since the core mod "playlistmanager" could do almost the same.
Your playlists will still be there no matter how they're created or whether mod installed.

**Comment by xJon** [comment]
Oh I see, apologies for the misunderstanding.
In this case I'll just update to 1.24, thank you for the detailed response!
Thank you for PlaylistEditor nevertheless as I've gained a lot of value from using it up until now.
